{% set name = "agate" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d9655bdebbfd61a71768202e1fb4847d6bba51f1800582da5c64c958952f4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - six >=1.9.0
    - pytimeparse >=1.1.5
    - parsedatetime !=2.5,!=2.6,>=2.1
    - babel >=2.0
    - isodate >=0.5.4
    - python-slugify >=1.2.1
    - leather >=0.3.2
    - future
    - pyicu           # [unix]
    - python-tzdata   # [win]
    - __win           # [win]
    - __unix          # [unix]

test:
  imports:
    - agate
    - agate.aggregations
    - agate.computations
    - agate.data_types
    - agate.table
    - agate.tableset
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://agate.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A data analysis library that is optimized for humans instead of machines.
  doc_url: http://agate.rtfd.org/
  dev_url: http://agate.rtfd.org/

extra:
  recipe-maintainers:
    - jan-janssen
