{%set name = "agate" %}
{%set version = "1.6.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "1547eb66a4caaea08cc247077e5b3740629be6724a047c94be0ecbbfa52ceb0a" %}
{%set build_num = "2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.9.0
    - pytimeparse >=1.1.5
    - parsedatetime >=2.1
    - babel >=2.0
    - isodate >=0.5.4
    - python-slugify >=1.2.1
    - leather >=0.3.2

test:
  imports:
    - agate
    - agate.aggregations
    - agate.computations
    - agate.data_types
    - agate.table
    - agate.tableset

about:
  home: http://agate.readthedocs.org/
  license: MIT
  license_family: MIT
  license: COPYING
  summary: 'A data analysis library that is optimized for humans instead of machines.'
  doc_url: http://agate.rtfd.org/
  dev_url: http://agate.rtfd.org/

extra:
  recipe-maintainers:
    - pmlandwehr
