{% set name = "agate" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 365c135f43ba20131e1be7501cd8f6a34031e1d5bcde21bf965e0cec45fe5a73

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six >=1.9.0
    - pytimeparse >=1.1.5
    - parsedatetime !=2.5,!=2.6,>=2.1
    - babel >=2.0
    - isodate >=0.5.4
    - python-slugify >=1.2.1
    - leather >=0.3.2
    - future
    - pyicu           # [unix]
    - python-tzdata   # [win]
    - __win           # [win]
    - __unix          # [unix]

test:
  imports:
    - agate
    - agate.aggregations
    - agate.computations
    - agate.data_types
    - agate.table
    - agate.tableset
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://agate.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A data analysis library that is optimized for humans instead of machines.
  doc_url: http://agate.rtfd.org/
  dev_url: http://agate.rtfd.org/

extra:
  recipe-maintainers:
    - jan-janssen
