{% set name = "agate" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 901b65382da982cfb52912246fb0ff3457d3ac02b94fafd4b10b0bff3ec358c5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six >=1.9.0
    - pytimeparse >=1.1.5
    - parsedatetime !=2.5,!=2.6,>=2.1
    - babel >=2.0
    - isodate >=0.5.4
    - python-slugify >=1.2.1
    - leather >=0.3.2
    - pyicu  # [unix]
    - future

test:
  imports:
    - agate
    - agate.aggregations
    - agate.computations
    - agate.data_types
    - agate.table
    - agate.tableset
  commands:
    - pip check  # [unix]
  requires:
    - pip

about:
  home: http://agate.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A data analysis library that is optimized for humans instead of machines.
  doc_url: http://agate.rtfd.org/
  dev_url: http://agate.rtfd.org/

extra:
  recipe-maintainers:
    - jan-janssen
