travis:
  secure:
    BINSTAR_TOKEN: P8iJH3uMOrBV2IAQKrsjiu18dumLYoU0kub4culhZ9guQdF5wflfk7oesvZiGPGTgkxWNAR5RYdYRadCHNt3ttK4SaQnur6tT4S+5iwTcljmmQIDt2NZeWJMDaDIQ+dVoEB/3oTSFnk+HBs7rxbotdNJZyqW7nxQVZBqVYYTAWj7lOtNdk4QEF63YAlVdKNRZVm/aE2VXrC81XlL3hkfs3a+mTG41OC0A+zwCmLB4Mt0f61rs/zdLc2eJtrXwHiJxL1LEBZ1GLXEZ2TSjJgbod3V5NoAoAf0xRlArzanCidH5VV0QIhiwgn/1O/Ku/0blvW7Zt9le/vEfPMjpw81o28NaqQTU31h6NYQH1yRFZ76jEGFIDec2Gx+Z0NN84REd9DKkwFNZzYcgA/w4vEC2ouoGjf5vXeClnO9X9ov6/l6auiU5QfSX2rY04eI0ODhHX0YFenw5bg40frAf6ea+4TGSgxgDdWwWsSgQB08u4gX+m05eA+SBNYqops2ZZq7ndSm3XULW8oUhKHhU/Qkr2kMZa1MFPLXWehUaxIz1XzK5em8oeynFEgwU9oM5MpOj9HMXIB0BXOJtpniBgrvwWzrC34Wlmp3vzEu3yLL/LZyhlNMulIAdo0DoXmPedlYyIUu0yZeSrekwY3J1xK5QVubSn7/17J+vnnWSDl+83o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
